// PMD axis initialization source code generated by Pro-Motion version 6.00  
//
// Compatible with C-Motion version 5.7
//

#include "C-Motion.h"
#include "PMDdiag.h"
#include "PMDsys.h"
#include "PMDutil.h"

// N-Series ION DD481S0056/18
PMDresult SetupAxis1(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;
PMDprintf("Apple\r\n");
  PMD_RESULT(PMDSetSampleTime (phAxis, 51))
  PMD_RESULT(PMDSetMotorType (phAxis, 0))
  PMD_RESULT(PMDResetEventStatus (phAxis, 0x0000))
  PMD_RESULT(PMDSetCommutationParameter (phAxis, PMDCommutationParameterPhaseCounts, 360))
  PMD_RESULT(PMDSetPositionErrorLimit (phAxis, 65535))
  PMD_RESULT(PMDSetSettleTime (phAxis, 0))
  PMD_RESULT(PMDSetSettleWindow (phAxis, 0))
  PMD_RESULT(PMDSetTrackingWindow (phAxis, 0))
  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetGearMaster (phAxis, 0, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopKp, 40))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopKi, 2))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopIlimit, 1000000))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopKd, 4500))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopDerivativeTime, 1))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopKout, 65535))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopKvff, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopKaff, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1Enable, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1B0, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1B1, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1B2, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1A1, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1A2, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad1K, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2Enable, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2B0, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2B1, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2B2, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2A1, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2A2, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, PMDPositionLoopBiquad2K, 0))
  PMD_RESULT(PMDSetMotorBias (phAxis, 0))
  PMD_RESULT(PMDSetMotorLimit (phAxis, 1456))
  PMD_RESULT(PMDSetMotionCompleteMode (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x1000))
  PMD_RESULT(PMDSetCaptureSource (phAxis, 1))
  PMD_RESULT(PMDSetCommutationParameter (phAxis, PMDCommutationParameterPhaseDenominator, 1))
  PMD_RESULT(PMDSetCommutationMode (phAxis, 1))
  PMD_RESULT(PMDSetPhaseCorrectionMode (phAxis, 0))
  PMD_RESULT(PMDSetPhaseInitializeMode (phAxis, 0))
  PMD_RESULT(PMDSetPhasePrescale (phAxis, 0))
  PMD_RESULT(PMDSetPhaseParameter (phAxis, PMDPhaseParameterRampTime, 0))
  PMD_RESULT(PMDSetPhaseParameter (phAxis, PMDPhaseParameterPositivePulseTime, 0))
  PMD_RESULT(PMDSetPhaseParameter (phAxis, PMDPhaseParameterNegativePulseTime, 0))
  PMD_RESULT(PMDSetPhaseParameter (phAxis, PMDPhaseParameterPulseCommand, 0))
  PMD_RESULT(PMDSetPhaseParameter (phAxis, PMDPhaseParameterRampCommand, 0))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0x0000, 0x00000000))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0x0001, 0x00000000))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0x0000, 0, 0, 0))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0x0001, 0, 0, 0))
  PMD_RESULT(PMDSetAuxiliaryEncoderSource (phAxis, 0, 0))
  PMD_RESULT(PMDSetCurrentControlMode (phAxis, 2))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 0, 423))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 1, 2162))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 2, 16383))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 0, 0))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 1, 0))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 2, 23170))
  PMD_RESULT(PMDSetAxisOutMask (phAxis, 0, 0, 0x0001, 0x0000))
  PMD_RESULT(PMDSetFaultOutMask (phAxis, 0x0600))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterOvervoltageLimit, 3000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterUndervoltageLimit, 1800))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, PMDCurrentFoldbackContinuousCurrentLimit, 910))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, PMDCurrentFoldbackI2tEnergyLimit, 485))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventPositiveLimit, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventNegativeLimit, 0x0000))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventMotionError, 0x0005))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventCurrentFoldback, 0x0007))
  PMD_RESULT(PMDSetDrivePWM (phAxis, PMDDrivePWMLimit, 16384))
  PMD_RESULT(PMDSetDrivePWM (phAxis, PMDDrivePWMFrequency, 10000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterTemperatureLimit, 19200))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterTemperatureHysteresis, 1280))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterShuntVoltage, 65535))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterShuntPWMDutyCycle, 0))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterBusCurrentReturnLimit, 65534))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventBrakeAsserted, 0x000a))
  PMD_RESULT(PMDUpdate (phAxis))
  PMD_RESULT(PMDSetOperatingMode (phAxis, 0x0037))
  PMD_RESULT(PMDSetGearRatio (phAxis, 0x00000000))

  return result;
}

PMDresult SetupAxis2(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;

  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0000))

  return result;
}

