
# Target file name (without extension).
TARGET = nIONCME

# Add any additional source files here
PROJECTFILES += Pro-MotionExport1_15_25.c
PROJECTFILES += Examples.c
PROJECTFILES += PassiveMode2.c
PROJECTFILES += LoadCellFunctions.c
PROJECTFILES += HomeCapture.c
PROJECTFILES += ReverseMove.c
PROJECTFILES += ComFunctions.c
PROJECTFILES += Assistive2.c
PROJECTFILES += Admittance2.c
PROJECTFILES += ResistTorqueGoal2.c
PROJECTFILES += StepResponse.c
PROJECTFILES += LoadCellCME.c
PROJECTFILES += AssistiveForce.c
PROJECTFILES += SaveOnly.c
PROJECTFILES += Transparent.c
PROJECTFILES += Impedance.c
PROJECTFILES += AssistTrajectory.c
PROJECTFILES += ReturnHome.c
PROJECTFILES += EKF.c

OFFSETDIR=../../

include $(OFFSETDIR)makefile
